"""
EPI Demo Script - AI Workflow Version with Steps
This demonstrates API calls with automatic redaction
"""
import time
import os

def print_step(step_num, description):
    """Print a clearly formatted step"""
    print(f"\n{'='*70}")
    print(f"STEP {step_num}: {description}")
    print(f"{'='*70}\n")

def print_substep(description):
    """Print a substep"""
    print(f"  → {description}")

# ============================================================================
# STEP 1: Environment Setup
# ============================================================================
print_step(1, "Setting Up AI Environment")
print_substep("Checking API credentials...")

api_key = os.getenv("OPENAI_API_KEY")
if api_key:
    # Show first/last 4 chars only (EPI will redact the full key anyway)
    masked = f"{api_key[:4]}...{api_key[-4:]}"
    print(f"  ✓ API Key found: {masked}")
else:
    print("  ⚠️  No API key found (set OPENAI_API_KEY environment variable)")
    print("  ℹ️  Demo will continue with mock responses...")

time.sleep(1)

# ============================================================================
# STEP 2: Initialize AI Client
# ============================================================================
print_step(2, "Initializing AI Client")

use_real_api = bool(api_key)

if use_real_api:
    try:
        from openai import OpenAI
        print_substep("Loading OpenAI SDK...")
        client = OpenAI(api_key=api_key)
        print("  ✓ OpenAI client initialized")
    except ImportError:
        print("  ⚠️  OpenAI package not found. Install with: pip install openai")
        use_real_api = False
else:
    print("  ℹ️  Using mock mode (no real API calls)")

time.sleep(1)

# ============================================================================
# STEP 3: Prepare AI Prompts
# ============================================================================
print_step(3, "Preparing AI Prompts")

prompts = [
    {
        "id": 1,
        "task": "Explain Quantum Computing",
        "prompt": "Explain quantum computing in one simple sentence."
    },
    {
        "id": 2,
        "task": "Generate Code",
        "prompt": "Write a Python function to calculate fibonacci numbers."
    }
]

print(f"  📝 Loaded {len(prompts)} prompts:")
for p in prompts:
    print(f"     {p['id']}. {p['task']}")

time.sleep(1)

# ============================================================================
# STEP 4: Execute AI Calls
# ============================================================================
print_step(4, "Executing AI API Calls")

responses = []

for prompt_data in prompts:
    print(f"\n  🤖 Processing Prompt #{prompt_data['id']}: {prompt_data['task']}")
    print(f"     Query: \"{prompt_data['prompt']}\"")
    
    time.sleep(0.5)
    
    if use_real_api:
        try:
            print("     → Calling OpenAI API...")
            response = client.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "user", "content": prompt_data['prompt']}
                ],
                max_tokens=150
            )
            result_text = response.choices[0].message.content
            print("     ✓ Response received")
        except Exception as e:
            result_text = f"[Error: {str(e)}]"
            print(f"     ✗ API Error: {str(e)}")
    else:
        # Mock responses
        mock_responses = {
            1: "Quantum computing uses quantum bits (qubits) that can exist in multiple states simultaneously, enabling exponentially faster processing for certain problems.",
            2: "def fibonacci(n):\n    if n <= 1:\n        return n\n    return fibonacci(n-1) + fibonacci(n-2)"
        }
        result_text = mock_responses.get(prompt_data['id'], "Mock response")
        print("     ✓ Mock response generated")
        time.sleep(0.5)
    
    responses.append({
        'prompt': prompt_data['task'],
        'response': result_text
    })

# ============================================================================
# STEP 5: Save AI Outputs
# ============================================================================
print_step(5, "Saving AI Outputs to Files")

# Save individual responses
for i, resp in enumerate(responses, 1):
    filename = f"ai_response_{i}.txt"
    print(f"  💾 Writing {filename}...")
    
    with open(filename, "w", encoding="utf-8") as f:
        f.write("=" * 70 + "\n")
        f.write(f"AI RESPONSE - {resp['prompt']}\n")
        f.write("=" * 70 + "\n\n")
        f.write(resp['response'])
        f.write("\n\n" + "=" * 70 + "\n")
        f.write("Generated by EPI Demo - Cryptographically Signed\n")
    
    print(f"     ✓ Saved: {filename}")

# Save consolidated report
print("\n  📊 Creating consolidated report...")
with open("ai_workflow_complete.txt", "w", encoding="utf-8") as f:
    f.write("╔" + "═" * 68 + "╗\n")
    f.write("║" + " " * 20 + "AI WORKFLOW REPORT" + " " * 30 + "║\n")
    f.write("╚" + "═" * 68 + "╝\n\n")
    
    f.write(f"Total Prompts Processed: {len(responses)}\n")
    f.write(f"API Mode: {'Real OpenAI API' if use_real_api else 'Mock Mode'}\n")
    f.write(f"Files Generated: {len(responses) + 1}\n\n")
    
    for i, resp in enumerate(responses, 1):
        f.write(f"\n{'─' * 70}\n")
        f.write(f"Response {i}: {resp['prompt']}\n")
        f.write(f"{'─' * 70}\n")
        f.write(resp['response'][:200])  # First 200 chars
        if len(resp['response']) > 200:
            f.write("...\n")
        f.write("\n")

print("     ✓ Saved: ai_workflow_complete.txt")
time.sleep(0.5)

# ============================================================================
# STEP 6: Demo Complete
# ============================================================================
print_step(6, "Workflow Complete - Review EPI Capture")

print("""
🎉 AI Workflow Demo Complete!

EPI has recorded:
  ✓ All API calls (with automatic key redaction)
  ✓ Generated files: ai_response_1.txt, ai_response_2.txt, ai_workflow_complete.txt
  ✓ Full console logs
  ✓ Execution timeline
  ✓ Environment state

🔐 Security Features:
  • API keys automatically redacted in logs
  • All data cryptographically signed
  • Tamper-evident verification
  • No external dependencies for viewing

👀 Next: Run 'epi view <filename.epi>' to see the interactive timeline!
""")

print("\n" + "━" * 70)
print("  EPI: The Standard for Verifiable AI Evidence")
print("━" * 70 + "\n")
