import json
import sys
sys.stdout.reconfigure(encoding='utf-8')

NB_PATH = r"c:\Users\dell\epi-recorder\epi_investor_demo_ULTIMATE.ipynb"

with open(NB_PATH, 'r', encoding='utf-8') as f:
    nb = json.load(f)

print("🔧 Implementing AUTHENTIC EPI Viewer extraction...")

# NEW VIEWER CELL: Extract and use the REAL viewer.html
authentic_viewer_source = [
    "# @title 🖥️ Launch Authentic EPI Viewer { display-mode: \"form\" }\n",
    "import zipfile\n",
    "import json\n",
    "import html\n",
    "import os\n",
    "from pathlib import Path\n",
    "from IPython.display import display, HTML\n",
    "\n",
    "# 1. Find the .epi file\n",
    "epi_files = list(Path('.').glob('*.epi')) + list(Path('.').glob('epi-recordings/*.epi'))\n",
    "epi_file = Path(max(epi_files, key=os.path.getmtime)) if epi_files else None\n",
    "\n",
    "print(f\"🔓 Extracting Authentic Viewer from: {epi_file}...\")\n",
    "\n",
    "if not epi_file or not epi_file.exists():\n",
    "    display(HTML('<h2 style=\"color: #ef4444;\">❌ No .epi file found - run Step 3 first</h2>'))\n",
    "else:\n",
    "    viewer_html = None\n",
    "    signature_display = \"UNSIGNED\"\n",
    "    \n",
    "    try:\n",
    "        with zipfile.ZipFile(epi_file, 'r') as z:\n",
    "            print(f\"   📦 Archive contains: {len(z.namelist())} files\")\n",
    "            \n",
    "            # Extract signature for display\n",
    "            if 'manifest.json' in z.namelist():\n",
    "                manifest = json.loads(z.read('manifest.json').decode('utf-8'))\n",
    "                raw_sig = manifest.get('signature', '')\n",
    "                if ':' in raw_sig:\n",
    "                    parts = raw_sig.split(':')\n",
    "                    # Show: ED25519...abc123\n",
    "                    signature_display = f\"{parts[0].upper()}...{parts[-1][:12]}\"\n",
    "                print(f\"   🔐 Signature: {signature_display}\")\n",
    "            \n",
    "            # PRIORITY: Extract the REAL viewer.html from the ZIP\n",
    "            html_files = [f for f in z.namelist() if f.endswith('.html')]\n",
    "            \n",
    "            if html_files:\n",
    "                viewer_file = html_files[0]  # Usually 'viewer.html'\n",
    "                print(f\"   ✨ Found authentic viewer: {viewer_file}\")\n",
    "                viewer_html = z.read(viewer_file).decode('utf-8', errors='ignore')\n",
    "                \n",
    "                # Inject signature if there's a placeholder\n",
    "                if '__SIGNATURE__' in viewer_html:\n",
    "                    viewer_html = viewer_html.replace('__SIGNATURE__', signature_display)\n",
    "                \n",
    "                print(f\"   📄 Viewer size: {len(viewer_html)} chars\")\n",
    "            else:\n",
    "                print(\"   ⚠️ No HTML viewer found in archive\")\n",
    "                print(\"   Available files:\", z.namelist())\n",
    "    \n",
    "    except Exception as e:\n",
    "        print(f\"   ❌ Extraction error: {e}\")\n",
    "    \n",
    "    # Render the AUTHENTIC viewer\n",
    "    if viewer_html:\n",
    "        # Display in iframe for isolation\n",
    "        escaped_html = html.escape(viewer_html)\n",
    "        iframe_code = f'''\n",
    "        <div style=\"border: 2px solid #10b981; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.1);\">\n",
    "            <div style=\"background: #10b981; color: white; padding: 8px 16px; font-weight: bold; display: flex; justify-content: space-between; align-items: center;\">\n",
    "                <span>🛡️ AUTHENTIC EPI VIEWER</span>\n",
    "                <span style=\"font-family: monospace; font-size: 11px; background: rgba(255,255,255,0.2); padding: 4px 8px; border-radius: 4px;\">{signature_display}</span>\n",
    "            </div>\n",
    "            <iframe \n",
    "                srcdoc=\"{escaped_html}\" \n",
    "                width=\"100%\" \n",
    "                height=\"600\" \n",
    "                style=\"border: none;\" \n",
    "                sandbox=\"allow-scripts allow-same-origin\"\n",
    "            ></iframe>\n",
    "        </div>\n",
    "        '''\n",
    "        print(\"\\n✅ Rendering authentic EPI viewer...\")\n",
    "        display(HTML(iframe_code))\n",
    "    else:\n",
    "        display(HTML('''\n",
    "        <div style=\"padding: 40px; text-align: center; border: 2px dashed #ef4444; border-radius: 8px; background: #fef2f2;\">\n",
    "            <h2 style=\"color: #ef4444; margin: 0;\">❌ Viewer Not Found</h2>\n",
    "            <p style=\"color: #7f1d1d; margin: 10px 0;\">The .epi file doesn't contain viewer.html</p>\n",
    "            <p style=\"color: #991b1b; font-size: 14px;\">This recording may have been created with an older version of EPI.</p>\n",
    "        </div>\n",
    "        '''))\n"
]

# Apply the fix\nfor cell in nb['cells']:\n    cid = cell.get('metadata', {}).get('id')\n    if cid == 'viewer':\n        cell['source'] = authentic_viewer_source\n        print(\"   ✅ Replaced with AUTHENTIC viewer extraction logic\")\n        break\n\nwith open(NB_PATH, 'w', encoding='utf-8') as f:\n    json.dump(nb, f, indent=2, ensure_ascii=False)\n\nprint(f\"\\n✨ Notebook updated: {NB_PATH}\")\nprint(\"\\nKEY CHANGE:\")\nprint(\"  OLD: Custom Tailwind CSS viewer (looked fake)\")\nprint(\"  NEW: Extracts REAL viewer.html from .epi ZIP (authentic)\")\nprint(\"\\nThe investor will see the ACTUAL EPI product interface!\")\n
